"""
Data Lakehouse Table Schema Definitions (Medallion Architecture)
Compatible with BigQuery and DuckDB.
"""
from typing import Dict, List, Any

# Column definitions for each Medallion Lakehouse Layer

BRONZE_RAW_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "batter": "BIGINT",
    "pitcher_name": "VARCHAR",
    "pitch_type": "VARCHAR",
    "release_speed": "DOUBLE",
    "release_pos_x": "DOUBLE",
    "release_pos_y": "DOUBLE",
    "release_pos_z": "DOUBLE",
    "release_spin_rate": "DOUBLE",
    "spin_axis": "DOUBLE",
    "pfx_x": "DOUBLE",
    "pfx_z": "DOUBLE",
    "plate_x": "DOUBLE",
    "plate_z": "DOUBLE",
    "vx0": "DOUBLE",
    "vy0": "DOUBLE",
    "vz0": "DOUBLE",
    "ax": "DOUBLE",
    "ay": "DOUBLE",
    "az": "DOUBLE",
    "sz_top": "DOUBLE",
    "sz_bot": "DOUBLE",
    "release_extension": "DOUBLE",
    "effective_speed": "DOUBLE",
    "events": "VARCHAR",
    "description": "VARCHAR",
    "balls": "INTEGER",
    "strikes": "INTEGER",
    "outs_when_up": "INTEGER",
    "inning": "INTEGER",
    "inning_topbot": "VARCHAR",
    "at_bat_number": "INTEGER",
    "pitch_number": "INTEGER",
    "pitch_name": "VARCHAR",
    "home_team": "VARCHAR",
    "away_team": "VARCHAR",
    "stand": "VARCHAR",
    "p_throws": "VARCHAR",
    "type": "VARCHAR",
    "woba_value": "DOUBLE",
    "woba_denom": "DOUBLE",
    "launch_speed": "DOUBLE",
    "launch_angle": "DOUBLE",
    "estimated_woba_using_speedangle": "DOUBLE"
}

SILVER_QUALIFIED_PITCHES_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "pitcher_name": "VARCHAR",
    "p_throws": "VARCHAR",
    "inning": "INTEGER",
    "at_bat_number": "INTEGER",
    "pitch_number": "INTEGER",
    "pitch_number_in_game": "INTEGER",
    "batter": "BIGINT",
    "stand": "VARCHAR",
    "pitch_type": "VARCHAR",
    "is_primary_pitch_type": "BOOLEAN",
    "release_speed": "DOUBLE",
    "release_pos_x": "DOUBLE",
    "release_pos_y": "DOUBLE",
    "release_pos_z": "DOUBLE",
    "release_extension": "DOUBLE",
    "release_spin_rate": "DOUBLE",
    "spin_axis": "DOUBLE",
    "pfx_x": "DOUBLE",
    "pfx_z": "DOUBLE",
    "plate_x": "DOUBLE",
    "plate_z": "DOUBLE",
    "vx0": "DOUBLE",
    "vy0": "DOUBLE",
    "vz0": "DOUBLE",
    "ax": "DOUBLE",
    "ay": "DOUBLE",
    "az": "DOUBLE",
    "events": "VARCHAR",
    "description": "VARCHAR",
    "balls": "INTEGER",
    "strikes": "INTEGER",
    "outs_when_up": "INTEGER",
    "type": "VARCHAR",
    "estimated_woba_using_speedangle": "DOUBLE",
    "launch_speed": "DOUBLE",
    "launch_angle": "DOUBLE",
    "woba_value": "DOUBLE",
    "woba_denom": "DOUBLE"
}

SILVER_BASELINES_SCHEMA: Dict[str, str] = {
    "pitcher": "BIGINT",
    "pitch_type": "VARCHAR",
    "as_of_game_pk": "BIGINT",
    "as_of_date": "DATE",
    "window_start_date": "DATE",
    "window_games_count": "INTEGER",
    "pitches_count": "INTEGER",
    "mean_release_pos_x": "DOUBLE",
    "std_release_pos_x": "DOUBLE",
    "mean_release_pos_z": "DOUBLE",
    "std_release_pos_z": "DOUBLE",
    "mean_release_extension": "DOUBLE",
    "std_release_extension": "DOUBLE",
    "mean_release_speed": "DOUBLE",
    "std_release_speed": "DOUBLE",
    "mean_release_spin_rate": "DOUBLE",
    "std_release_spin_rate": "DOUBLE",
    "mean_spin_axis": "DOUBLE",
    "std_spin_axis": "DOUBLE",
    "mean_pfx_x": "DOUBLE",
    "std_pfx_x": "DOUBLE",
    "mean_pfx_z": "DOUBLE",
    "std_pfx_z": "DOUBLE",
    "mean_vaa": "DOUBLE",
    "std_vaa": "DOUBLE",
    "covariance_matrix_json": "VARCHAR",
    "precision_matrix_json": "VARCHAR"
}

SILVER_FEATURES_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "pitcher_name": "VARCHAR",
    "pitch_number_in_game": "INTEGER",
    "inning": "INTEGER",
    "at_bat_number": "INTEGER",
    "pitch_type": "VARCHAR",
    # Level 0 Kinematics
    "vaa": "DOUBLE",
    "release_3d_dist_from_origin": "DOUBLE",
    # Level 1 Z-scores vs Historical Baseline
    "z_release_pos_x": "DOUBLE",
    "z_release_pos_z": "DOUBLE",
    "z_release_extension": "DOUBLE",
    "z_release_speed": "DOUBLE",
    "z_release_spin_rate": "DOUBLE",
    "z_spin_axis": "DOUBLE",
    "z_pfx_x": "DOUBLE",
    "z_pfx_z": "DOUBLE",
    "z_vaa": "DOUBLE",
    # Level 1 Rolling Trends
    "roll5_release_dist_drift": "DOUBLE",
    "roll10_release_dist_drift": "DOUBLE",
    "roll5_speed_std": "DOUBLE",
    "roll10_speed_std": "DOUBLE",
    "roll5_spin_axis_shift": "DOUBLE",
    "roll10_spin_axis_shift": "DOUBLE",
    "pitch_interval_sec": "DOUBLE",
    # Intra-game Shrinkage Calibrated Residuals
    "calib_delta_pos_x": "DOUBLE",
    "calib_delta_pos_z": "DOUBLE",
    "calib_delta_speed": "DOUBLE",
    "calib_delta_spin_axis": "DOUBLE",
    "calib_delta_vaa": "DOUBLE"
}

GOLD_ANOMALY_SCORES_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "pitcher_name": "VARCHAR",
    "pitch_number_in_game": "INTEGER",
    "inning": "INTEGER",
    "at_bat_number": "INTEGER",
    "pitch_type": "VARCHAR",
    "mahalanobis_raw": "DOUBLE",
    "mahalanobis_calibrated": "DOUBLE",
    "autoencoder_recon_loss": "DOUBLE",
    "combined_anomaly_score": "DOUBLE",
    "health_index": "DOUBLE",
    "dominant_drift_feature": "VARCHAR",
    "contrib_release_pct": "DOUBLE",
    "contrib_spin_pct": "DOUBLE",
    "contrib_movement_pct": "DOUBLE",
    "contrib_speed_pct": "DOUBLE"
}

GOLD_ALERT_EVENTS_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "pitcher_name": "VARCHAR",
    "alert_pitch_number": "INTEGER",
    "alert_inning": "INTEGER",
    "detector_type": "VARCHAR",
    "cusum_statistic": "DOUBLE",
    "cusum_threshold": "DOUBLE",
    "ewma_statistic": "DOUBLE",
    "ewma_upper_limit": "DOUBLE",
    "alert_level": "VARCHAR",
    "primary_drift_reason": "VARCHAR"
}

GOLD_COLLAPSE_LABELS_SCHEMA: Dict[str, str] = {
    "game_pk": "BIGINT",
    "game_date": "DATE",
    "pitcher": "BIGINT",
    "at_bat_number": "INTEGER",
    "pitch_number_in_game": "INTEGER",
    "inning": "INTEGER",
    "window_pa_count": "INTEGER",
    "window_blended_xwoba": "DOUBLE",
    "window_barrels_count": "INTEGER",
    "window_bb_hbp_count": "INTEGER",
    "window_hits_count": "INTEGER",
    "window_runs_count": "INTEGER",
    "is_collapse_event": "BOOLEAN",
    "collapse_reason": "VARCHAR"
}

GOLD_MODEL_EVALUATION_SCHEMA: Dict[str, str] = {
    "evaluation_id": "VARCHAR",
    "evaluated_at": "TIMESTAMP",
    "sample_games_count": "INTEGER",
    "total_pitches_analyzed": "INTEGER",
    "total_collapse_events": "INTEGER",
    "method_name": "VARCHAR",
    "lift_odds_ratio": "DOUBLE",
    "lead_time_mean_pitches": "DOUBLE",
    "lead_time_median_pitches": "DOUBLE",
    "lead_time_iqr_pitches": "DOUBLE",
    "pr_auc": "DOUBLE",
    "precision": "DOUBLE",
    "recall": "DOUBLE",
    "f1_score": "DOUBLE",
    "false_alarm_rate_per_start": "DOUBLE",
    "comparison_vs_naive_lift": "DOUBLE",
    "comparison_vs_naive_lead_time": "DOUBLE"
}
